### ISSUE TITLE
ckeditor-cloudinary-uploader-adapter. It was not possible to load the plugin.

### ISSUE THREAD

**Issue by n3nikita** [IyiKuyoro/ckeditor-cloudinary-image-adapter#10]
Hello. I've added **ckeditor-cloudinary-uploader-adapter** plugin to ckeditor by following [this tutorial](https://medium.com/swlh/a-detailed-approach-of-setting-up-ckeditor-with-angular-e546610157ba) and it works fine but after some time I got this errors:

![image](https://user-images.githubusercontent.com/22433209/66438264-7beb7580-ea2c-11e9-9185-f457ee4e2a06.png)

Here is my config:
```typescript
import * as BlockEditor from '@ckeditor/ckeditor5-build-balloon';
import { CloudinaryImageUploadAdapter } from 'ckeditor-cloudinary-uploader-adapter';

public textEditor = BlockEditor;
  public textConfig = {
    extraPlugins: [ this.TheUploadAdapterPlugin ],
    toolbar: [ 'heading', '|', 'bold', 'italic', 'link', 'blockQuote', 'numberedlist', 'bulletedlist', 'mediaembed', 'inserttable']
  }

  TheUploadAdapterPlugin(editor) {
    editor.plugins.get('FileRepository').createUploadAdapter = (loader) => {
      return new CloudinaryImageUploadAdapter(loader, '...', '...');
    };
  }
```

Error will disappear if I commet `extraPlugins` part.

**Comment by IyiKuyoro** [comment]
Hi @MrBandaruk 

Thanks for reaching out.

I have been unable to replicate this issue, kindly share the following information with me to help me investigate this further.

1. Is the above code in your component file or a separate config file?
2. What version of Node are you using?
3. What version of the library do you have installed?

**Comment by n3nikita** [comment]
Hello @IyiKuyoro 

Thank you for the reply.

1. This code in my component file.
2. Node version is `v10.15.0`
3. Library version is `^1.1.3`

**Comment by n3nikita** [comment]
I also tried to create new Cloudinary account and change strings `your_cloud_name`, `your_unsigned_upload_preset`. Error still exists.

**Comment by IyiKuyoro** [comment]
@MrBandaruk 

Thanks a lot for raising this issue and spending time on a call with me to find the source.

I have been able to narrow it down to a change that occurs in the `tsconfig.json` file when you update Angular to `8.2~`.

I am currently working on a fix which should be up later today.

Thanks again!

**Comment by IyiKuyoro** [comment]
@MrBandaruk 

While I work on fixing this in the package, you can change the typescript target to `"target": "es5",` in the `tsconfig.json` file. while using Angular >"7.~"

That should fix it.

**Comment by ghost** [comment]
Hello @IyiKuyoro

Same mistake in Angular 9
I tried to change "target": "es5", in the tsconfig.json but the error remains
Thanks for your help.

**Comment by IyiKuyoro** [comment]
Hi @ianraf 

Thanks for reaching out. I just tried to update the sample project of this package to Angular version 9 and it seems to work fine after changing the target to es5.

[Here is a link to the same project repo](https://github.com/IyiKuyoro/ckeditor-image-upload) kindly confirm that that does not work using the instructions for setting up and we can take a closer look. Perhaps there might be a version issue.

**Comment by ghost** [comment]
Thanks for the reply @IyiKuyoro
I canceled everything and started from 0
I downloaded your project and followed your instructions, now it works in yours.
Now I have to carry it all into my project.
I'll let you know how it goes in the next few days.
Thanks again for your availability.

**Comment by ghost** [comment]
Hi @IyiKuyoro

One more question, you could explain better how those numbers in square brackets are used, to have an acceptable result.
Thank you.

**Comment by IyiKuyoro** [comment]
Hi @ianraf,

Thanks for asking. Those numbers represent pixel sizes. They help with responsive image support for both Cloudinary and CKEditor. Basically based on the view width size, different image sizes are loaded from cloudinary.

To understand more about responsive images, kindly see [this](https://developers.google.com/web/fundamentals/design-and-ux/responsive/images).

**Comment by ghost** [comment]
Hi @IyiKuyoro

Thank you for having responded and clarified my doubts.
